### ISSUE TITLE
Are we excluding non-voters?

### ISSUE THREAD

**Issue by flaxter** [dougalsutherland/pummeler#12]
In the KDD paper I excluded those under 18 and non-citizens, but since we're now thinking about "group-based" modeling I think it's fine to include all residents, meaning kids and non-citizens, too. Just wanted to check what's happening in the code currently.

@dougalsutherland

**Comment by djsutherland** [comment]
It's an option, on by default; pass `voters_only=False` to `sort_by_region` or use `pummeler sort --all-people` to include everyone.
