### ISSUE TITLE
allocation flags

### ISSUE THREAD

**Issue by flaxter** [dougalsutherland/pummeler#15]
Should we be including all of these variables?

    FBDSP - Number of bedrooms allocation flag
    FBLDP - Units in structure allocation flag
    FBUSP - Business or medical office on property allocation flag

etc.

What do they mean?

**Comment by djsutherland** [comment]
https://usa.ipums.org/usa/flags.shtml

Basically it's an indicator for when they couldn't figure out the true value of a datum (if someone says they're married and also age 6, they'll manually figure out which of those is more likely to be true and edit the other, then mark the flag that they did that). It's not meaningless, but also probably pretty skippable.

**Comment by flaxter** [comment]
OK, I'm skipping. Anywhere I see info['alloc_flags'] in `sort.py / featurize.py` I can just get rid of it and that'll do it, right? Or I guess just setting `'alloc_flags' to be empty in reader.py?

**Comment by djsutherland** [comment]
If you delete it in `reader` it'll cause an error (it asserts that all the fields were used). Easiest place to drop it is in featurize; then if you change your mind later you don't have to rerun the sort step.

**Comment by djsutherland** [comment]
@flaxter Actually there's already a `skip_feats` argument to `get_embeddings`; you could default it to the set of alloc flags.

**Comment by flaxter** [comment]
true, but it's a long list to put on the command-line

**Comment by flaxter** [comment]
anyway, I can just exclude them when I fit the model, since I'm not featurizing categorical variables beyond the one-hot encoding
