### ISSUE TITLE
CLI issue

### ISSUE THREAD

**Issue by flaxter** [dougalsutherland/pummeler#18]
$ python pummel featurize --seed 1 --skip-feats POWSP regions
usage: pummel featurize [-h] [--chunksize LINES] [--skip-rbf]
                        [--n-freqs N_FREQS] [--bandwidth BANDWIDTH]
                        [--rff-orthogonal | --rff-normal] [--seed SEED]
                        [--skip-feats FEAT_NAME [FEAT_NAME ...]]
                        dir [outfile]
pummel featurize: error: too few arguments

**Comment by flaxter** [comment]
This works:

`$ python pummel featurize --seed 1 regions`

**Comment by flaxter** [comment]
As does this:

`$ python pummel featurize --skip-feats POWSP --seed 1 regions`

**Comment by djsutherland** [comment]
It's a slightly unintuitive behavior of argparse; it's trying to interpret `regions` as another argument to `--skip-feats`. You can do it with 

`python pummel featurize --seed 1 --skip-feats POWSP -- regions`.
